services:
  db:
    image: postgres:15-alpine
    container_name: wl_api_db
    environment:
      POSTGRES_USER: umar
      POSTGRES_PASSWORD: umar2611
      POSTGRES_DB: wl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
